"""empty message

Revision ID: f5364cc8b250
Revises: 
Create Date: 2019-08-18 14:28:20.432385

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5364cc8b250'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pembeli')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pembeli',
    sa.Column('id_pembeli', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nama_pembeli', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('contact_pembeli', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email_pembeli', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('password_pembeli', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_pembeli'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
